// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: services/otp/otp.proto

package otp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OtpServiceClient is the client API for OtpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OtpServiceClient interface {
	CreateOtp(ctx context.Context, in *CreateOtpRequest, opts ...grpc.CallOption) (*Otp, error)
	GetOtp(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*Otp, error)
	DelOtp(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type otpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOtpServiceClient(cc grpc.ClientConnInterface) OtpServiceClient {
	return &otpServiceClient{cc}
}

func (c *otpServiceClient) CreateOtp(ctx context.Context, in *CreateOtpRequest, opts ...grpc.CallOption) (*Otp, error) {
	out := new(Otp)
	err := c.cc.Invoke(ctx, "/otp.OtpService/CreateOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otpServiceClient) GetOtp(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*Otp, error) {
	out := new(Otp)
	err := c.cc.Invoke(ctx, "/otp.OtpService/GetOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otpServiceClient) DelOtp(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/otp.OtpService/DelOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OtpServiceServer is the server API for OtpService service.
// All implementations must embed UnimplementedOtpServiceServer
// for forward compatibility
type OtpServiceServer interface {
	CreateOtp(context.Context, *CreateOtpRequest) (*Otp, error)
	GetOtp(context.Context, *OtpRequest) (*Otp, error)
	DelOtp(context.Context, *OtpRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedOtpServiceServer()
}

// UnimplementedOtpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOtpServiceServer struct {
}

func (UnimplementedOtpServiceServer) CreateOtp(context.Context, *CreateOtpRequest) (*Otp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOtp not implemented")
}
func (UnimplementedOtpServiceServer) GetOtp(context.Context, *OtpRequest) (*Otp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOtp not implemented")
}
func (UnimplementedOtpServiceServer) DelOtp(context.Context, *OtpRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelOtp not implemented")
}
func (UnimplementedOtpServiceServer) mustEmbedUnimplementedOtpServiceServer() {}

// UnsafeOtpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OtpServiceServer will
// result in compilation errors.
type UnsafeOtpServiceServer interface {
	mustEmbedUnimplementedOtpServiceServer()
}

func RegisterOtpServiceServer(s grpc.ServiceRegistrar, srv OtpServiceServer) {
	s.RegisterService(&OtpService_ServiceDesc, srv)
}

func _OtpService_CreateOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtpServiceServer).CreateOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.OtpService/CreateOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtpServiceServer).CreateOtp(ctx, req.(*CreateOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtpService_GetOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtpServiceServer).GetOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.OtpService/GetOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtpServiceServer).GetOtp(ctx, req.(*OtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtpService_DelOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtpServiceServer).DelOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.OtpService/DelOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtpServiceServer).DelOtp(ctx, req.(*OtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OtpService_ServiceDesc is the grpc.ServiceDesc for OtpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OtpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otp.OtpService",
	HandlerType: (*OtpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOtp",
			Handler:    _OtpService_CreateOtp_Handler,
		},
		{
			MethodName: "GetOtp",
			Handler:    _OtpService_GetOtp_Handler,
		},
		{
			MethodName: "DelOtp",
			Handler:    _OtpService_DelOtp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/otp/otp.proto",
}
